### ISSUE TITLE
Idea about convenient for reduction

### ISSUE THREAD

**Issue by timothypratley** [noprompt/meander#102]
Aggregation is a useful concept when manipulating data.
Can `reduce` have a pattern representation?
A pattern can obviously be used to describe the source and the target, but the aggregation part fits in between as a function application.

Consider the most basic Clojure reduction:

```clojure
(reduce + 0 data)
```

Can this be more visual?

```clojure
(>>> data + 0)
```

* the >>> glyph visually/structurally communicates condensing
* condensing is directional, from a sequence, using +, into 0

What might this look like as a meander pattern?

```clojure
(>>> [*x ...] (+ *x) 0 ?sum)
```

* Instead of an input sequence, we are matching a sequence 
* `?sum` is establishing a variable which will be bound to the final aggregate
* `(+ *x)` is a reducing thread form that expands as  `(fn [**acc** _] (-> **acc** (+ *x)))`
  - We don't need the second input of the reducer because sequence bindings are already in scope
  - `**acc**` is bound to `0` initially and updated by each step for the reducing thread
  - `?sum` is the last value `**acc**` stores
  - `(+ *x)` can be threaded through other threads `(-> (+ *x) (->> / 3) (doto (prn "zz")))` which is to say you can express a lot without resorting to a function. And you can still resort to a function if you prefer.

Let's consider a more complicated example:

```clojure
(>>> (m/seqable [*num (m/seqable [*lang *word] ...)] ...)
     (assoc-in [*lang *word] *num)
     {}
     ?by-lang)
```

* The sequence pattern will match things of the shape `{:num {:lang :word}}`
* The reducing thread body expands to `(assoc-in **acc** [lang word] num)` which will build a map of shape `{:lang {:word :num}}`
* We are accumulating into an empty map
* The final value of **acc** will be bound to `?by-lang`

We could further simplify the sequence pattern match as:

```clojure
(>>> (for [*num (for [*lang *word])])
     (assoc-in [*lang *word] *num)
     {}
     ?by-lang)
```

Here `for` is a syntax that expands to `seqable` but in a little more concise way and potential with some unique features similar to Clojure `for` such as unnesting. This idea relevant to the extent that reductions and `for` expressions will often be found together.

FWIW I think this expression is beautiful.

Let's now backtrack and see how this would have looked in Clojure:

```clojure
(reduce
 (fn [acc [num lang word]]
   (assoc-in acc [lang num] word))
 {}
 (for [[num m] **data**
       [lang word] m]
   [num lang word]))
```

Honestly not too bad, it is concise, but qualitatively the pattern feels much more visual and directly reflective of the structures being processed and produced.

Meander has most of the tools in place to do this already:

```clojure
(m/match [1 2 3]
         [(m/and !x (m/app #(+ (last !x) %) !acc)) ...]
         (last !acc))
#_#_=> 6
```

I could define a syntax that expands out to this kind of expression I think, except for 1 thing I'm not sure how to do... I can't get a mutable variable out so instead I simulated that using `!acc`. Is there a reason we aren't allowed to get mutable variables, or a way I don't understand?

I'll try to come up with a `defsyntax` for it.

## Symmetry and directionality

It's not immediately clear to me if `(>>> ,,,)` appeared in a substitution whether it implies inserting a sequence that matches the reduction constraint, or just the final expression.

* Insert a sequence interesting but hard constraint problem... can you find a sequence of numbers that add up to 6? Yeah... but there are a lot of them, and not all reducers are reversible.
* Insert final expression; easy but kind of cheating? You won't get out what you put in.

So I'm inclined to say there would be no substitution version just accept that they are one way.

**Comment by timothypratley** [comment]
## Implementation attempt (failed)

```
(m/defsyntax >>> [xs fthread init result]
  (cond
    (m/match-syntax? &env)
    (doto
     `(m/and
       (m/let [~'**acc** ~init])
       ~(assoc xs 0 `(m/and
                      ~(first xs)
                      (m/app (fn [~'_] (-> ~'**acc** ~fthread))
                             ~'**acc**)))
       (m/let [~result ~'**acc**]))
      (prn :debug))

    :else
    &form))

(m/match [1 2 3]
         (>>> [*x ...] (+ *x) 0 ?sum)
         ?sum)

Expands to:
(meander.epsilon/and (meander.epsilon/let [**acc** 0]) [(meander.epsilon/and *x (meander.epsilon/app (clojure.core/fn [_] (clojure.core/-> **acc** (+ *x))) **acc**)) ...] (meander.epsilon/let [?sum **acc**]))

=> 0
```
Trying this revealed a further complication... how can I insert the function application in the innermost spot??

**Comment by noprompt** [comment]
In my opinion, the best way to do a reduction is with `m/rewrite` and `m/cata` on the right, or with a strategy based reduction.

Here's an example of how I typically do `rewrite` based reductions.

```clj
(m/rewrite [() '(1 2 3)] ;; Initial state
  ;; Intermediate step with recursion
  [?current (?head & ?tail)]
  (m/cata [(?head & ?current) ?tail])

  ;; Done
  [?current ()]
  ?current)
;; => (3 2 1)
 ```

If you wanted to `(m/app f)` somewhere in there you could do that.

```clj
(m/cata [(m/app f ?current ?head) ?tail])
```

Here is how you might do a reduction with a strategy.

```clj
(m*/pipe build-initial-state (m*/until = step) ,,,)
```

I prefer doing reductions in the style above because their structured nature lends to thinking more in terms of calculating with symbols and structures, rather than computing with functions.

**Comment by timothypratley** [comment]
Applying your approach back to the examples I presented:

```clojure
(defn sum [nums]
  (m/rewrite
   [0 nums] ;; Initial state
   
   [?acc [?head & ?tail]] ;; Values remaining
   (m/cata [~(+ ?acc ?head) ?tail])    ;; Reduce
   
   [?acc []] ;; Empty
   ?acc ;; Done
   ))

(sum [1 2 3 4 5])
;;=> 15
```

```clojure
(def data
  {1 {:en "one", :de "eins", :fr "un"}
   2 {:en "two", :de "zwei", :fr "deux" :es "dos"}
   3 {:en "three", :de "drei", :fr "trois"}
   5 {:fr "cinq"}})

(defn k [data]
  (m/rewrite
   [{} data] ;; Initial state

   [?acc {?num {:as ?inner} & ?more-outer}] ;; Values remaining
   (m/cata
    [?acc ?more-outer ?num ?inner])

   [?acc ?more-outer ?num {?lang ?word & ?more-inner}]
   (m/cata
    [~(assoc-in ?acc [?lang ?num] ?word) ?more-outer ?num ?more-inner]) ;; Reduce inner

   [?acc ?more-outer _ {}] ;; Done with inner
   (m/cata
    [?acc ?more-outer]) ;; Recur outer

   [?acc {}] ;; Empty
   ?acc ;; Done
   ))

(k data)
#_#_=> 
{:de {3 "drei", 1 "eins", 2 "zwei"},
 :fr {3 "trois", 1 "un", 2 "deux", 5 "cinq"},
 :en {3 "three", 1 "one", 2 "two"},
 :es {2 "dos"}}
```

These things jump out to me:

1. Yes! this works and accurately describes the algorithm for traversal and computation 😄
2. I am dissatisfied with it.
3. This is now code that describes state, inputs, outputs, and recursion. It is a self recursive multi-arity function. Meander has been demoted to the role of a better input destructure.
4. I would not write the Clojure solution as a self recursive multi-arity function even though I could. `reduce` is an abstract of recursion and state management. This solution incurs the cognitive overhead of explicit recursion and state management.

For reference here is the Clojure self-recursive multi-arity solution for sum only (I can't bring myself to write the map manipulation one!):
```clojure
(defn sum* "never do this"
  ([xs] (sum* 0 xs))
  ([acc [& xs]] (if xs
                  (recur (+ acc (first xs)) (rest xs))
                  acc)))
```

Beyond all that the really striking thing to me is that I lost sight of the original data, comments are necessary to keep track of where we are in the process and it was tedious to get everything aligned just right. I think it's safe to summarize that I find `m/cata` an unpalatable way to express reduction for the same reasons I find Clojure self recursive aggregations unpalatable. But it is amazing that this is achievable!

The fact that `m/cata` exists gives me a whole new avenue to pursue my hunch that Meander can have a higher-order abstraction of `reduce`.

I am very grateful you described this approach!

**Comment by timothypratley** [comment]
Here is a "working" `defsyntax` with one caveat: as a workaround to finding the "deepest variable" you have to nominate it instead. This adds one extra input, but at least it works!

```clojure
(defn replace [x in with]
  (m/find in
          (m/$ ?context (m/pred #{x}))
          (?context with)))

(m/defsyntax >>> [deepest-variable p reduce-step init result]
  (cond
    (m/match-syntax? &env)
    (doto
     `(m/and
       ~(replace deepest-variable p
                 `(m/and
                  ~deepest-variable
                  (m/app (fn [~'_] (-> (if (seq ~'!acc#) (last ~'!acc#) ~init) ~reduce-step))
                         ~'!acc#)))
       (m/let [~result (last ~'!acc#)]))
      (prn :debug))

    :else
    &form))
```

Now to use it:
```clojure
(m/match data
         (>>> *word
              {& (m/seqable [*num {& (m/seqable [*lang *word] ...)}] ...)}
              (assoc-in [*lang *word] *num)
              {}
              ?by-lang)
         ?by-lang)
#_#_=>
{:en {"one" 1, "two" 2, "three" 3},
 :de {"eins" 1, "zwei" 2, "drei" 3},
 :fr {"un" 1, "deux" 2, "trois" 3, "cinq" 5},
 :es {"dos" 2}}
```

Success!

**Comment by timothypratley** [comment]
Now going back the other direction, let's ask well couldn't that just be a regular Clojure macro?

```clojure
(defmacro >>> [bindings reduce-step init]
  `(let [acc# (atom ~init)]
     (doseq ~bindings
       (swap! acc# #(-> % ~reduce-step)))
     @acc#))

(>>> [x [1 2 3]] (+ x) 0)

(>>> [[num m] data
      [lang word] m]
     (assoc-in [lang num] word)
     {})
```
Obviously Clojure can have a very direct visual representation of `reduce` this way. It misses out on all the built-in operators but I'm starting to wonder if that really matters at all for reduction I find it hard to imagine a scenario where I would care about that.

**Comment by timothypratley** [comment]
Closing this issue as I'm not able to make a case for this or think of a way it can help meander.
