### ISSUE TITLE
Determine release process for Clojars

### ISSUE THREAD

**Issue by boxxxie** [noprompt/meander#14]

**Comment by noprompt** [comment]
@boxxxie I haven't made time to put together a release process for Clojars but I plan to look into it soon. It looks like it is possible to utilize this library via [this Leiningen plugin](https://github.com/RickMoynihan/lein-tools-deps) provided you have a `deps.edn` containing the following (or semantically equivalent).

```clj
{:deps
 {noprompt/meander
  {:git/url "https://github.com/noprompt/meander.git"
   :sha "642809df04b0977cf69d8e26616c47d69b382e4d"}}}
```

**Comment by boxxxie** [comment]
thanks. going down the rabbit whole with that plugin and deps.

I can bring meander into my project now

**Comment by noprompt** [comment]
@boxxxie Cool. Thanks for your patience. When I release the library to Clojars I’ll let you know.

**Comment by noprompt** [comment]
@boxxxie I've deployed a release to Clojars and put together a few scripts to make the process easy for me to repeat in the future. [Here's](https://clojars.org/meander/alpha) the Clojars page (I've also stuck their badge on the `README`).

I'll cut new releases whenever bugs are fixed or significant enhancements are made in the source. 👍

**Comment by boxxxie** [comment]
it's also common to have snapshot releases on clojars

**Comment by noprompt** [comment]
@boxxxie It certainly is, however, my plan to is to release jars such that `SNAPSHOT`s would be redundant. I'll push new jars whenever the source is modified and tests pass. This way I can get releases out frequently and without the need to push intermediate, potentially broken, `SNAPSHOT` versions.

I could release a `SNAPSHOT` simultaneously with each new jar which could serve as pointer to the latest version if that'd be helpful.
