### ISSUE TITLE
Link to Meander documentation is broken

### ISSUE THREAD

**Issue by dgr** [noprompt/meander#157]
The `README.md` file Documentation section links to `https://cljdoc.org/d/meander/epsilon/` which display an error: `API & Git import failed in build #37351`.

**Comment by noprompt** [comment]
According to the build failure the problem is

```
 No such namespace: meander.match.syntax.specs.epsilon, could not locate meander/match/syntax/specs/epsilon.cljs, meander/match/syntax/specs/epsilon.cljc, or JavaScript source providing "meander.match.syntax.specs.epsilon" in file /tmp/cljdoc-meander-epsilon-0.0.5335253192555867675969/contents/meander/match/check/specs/epsilon.cljc
```

which is a quick fix.

**Comment by noprompt** [comment]
I've fixed the broken `:require` clause and will make a new release sometime tomorrow.

**Comment by noprompt** [comment]
The docs for the most recent build are [here](https://cljdoc.org/d/meander/epsilon/0.0.543/doc/readme).
