### ISSUE TITLE
readme's let exemple throws

### ISSUE THREAD

**Issue by pbaille** [noprompt/meander#19]
I've got the following error evaluating this readme form:

```clj
(match 42
  (or [?x ?y] (let [?x ?y] [1 2]))
  [?x ?y])
;; ExceptionInfo non exhaustive pattern match  clojure.core/ex-info (core.clj:4739)
```

**Comment by noprompt** [comment]
Ha! Damn README examples! 😄 I’ll take a look and get it fixed.

**Comment by noprompt** [comment]
@pbaille I've fixed the issue and released a new jar. Thanks for the bug report!
