### ISSUE TITLE
Inability to use `&` on rhs

### ISSUE THREAD

**Issue by ribelo** [noprompt/meander#195]
```clojure
(m/rewrite {:a 1 :b 2 :c 3 :d 4}
  (m/map-of !ks !vs)
  {& [[!ks !vs] ...]})

;; =>
;; Syntax error macroexpanding m/rewrite ...
;; non exhaustive pattern match
```

**Comment by noprompt** [comment]
@ribelo This seems to be compiling and [passing](https://github.com/noprompt/meander/runs/3306017801) a [test](https://github.com/noprompt/meander/blob/epsilon/test/meander/epsilon_test.cljc#L2733) created it for it.
