### ISSUE TITLE
Performance issue with compiling a large Maybe pattern

### ISSUE THREAD

**Issue by xiongtx** [noprompt/meander#234]
# Problem

When matching maps with keys whose value could be `nil` or maps themselves, we use the [Maybe pattern](https://github.com/noprompt/meander/blob/55f5ce70e6ef717e95c58260f6bc725d70c0cb6d/doc/cookbook.md#the-maybe-pattern). E.g.

```clojure
(defn extract-optional-simple
  [m]
  (m/match m
    {:a (m/or (m/and nil ?a1) {:a1 ?a1})} ?a1))
```

When dealing w/ a large number of optional values, however, performance of compiling the function degrades rapidly. The following takes nearly 10s to evaluate on my MacBook Pro:

```clojure
(defn extract-optional-bad
  [m]
  (m/match m
    {:a (m/or (m/and nil ?a1) {:a1 ?a1})
     :b (m/or (m/and nil ?b1) {:b1 ?b1})
     :c (m/or (m/and nil ?c1) {:c1 ?c1})
     :d (m/or (m/and nil ?d1) {:d1 ?d1})
     :e (m/or (m/and nil ?e1) {:e1 ?e1})
     :f (m/or (m/and nil ?f1) {:f1 ?f1})
     :g (m/or (m/and nil ?g1) {:g1 ?g1})
     :h (m/or (m/and nil ?h1) {:h1 ?h1})
     :i (m/or (m/and nil ?i1) {:i1 ?i1})
     :j (m/or (m/and nil ?j1) {:j1 ?j1})}
    [?a1 ?b1 ?c1 ?d1 ?e1 ?f1 ?g1 ?h1 ?i1 ?j1]))
```

The performance of the function itself is fine, it just take a long time to compile.

# References

- `meander.epsilon` version: `0.0.650`
- Clojure version: `1.11.0`
- Machine specs:
<img width="247" alt="image" src="https://user-images.githubusercontent.com/1624090/177023232-57bb9002-8fd6-4c71-9b8d-38af4d966429.png">

**Comment by noprompt** [comment]
@xiongtx Thanks for the report. I am sorry this takes a while to compile. This is totally due to how `m/or` is compiled. This is likely generating a lot of code. Even when I try to macro expand the code, Cider times out.

Alternatively, you could try the following.


```clj
(defn extract-optional-bad
  [m]
  (vec
   (m/search m
     {:a (m/or (m/and nil ?a1) {:a1 ?a1})} ?a1
     {:b (m/or (m/and nil ?b1) {:b1 ?b1})} ?b1
     {:c (m/or (m/and nil ?c1) {:c1 ?c1})} ?c1
     {:d (m/or (m/and nil ?d1) {:d1 ?d1})} ?d1
     {:e (m/or (m/and nil ?e1) {:e1 ?e1})} ?e1
     {:f (m/or (m/and nil ?f1) {:f1 ?f1})} ?f1
     {:g (m/or (m/and nil ?g1) {:g1 ?g1})} ?g1
     {:h (m/or (m/and nil ?h1) {:h1 ?h1})} ?h1
     {:i (m/or (m/and nil ?i1) {:i1 ?i1})} ?i1
     {:j (m/or (m/and nil ?j1) {:j1 ?j1})} ?j1)))
```

This has the same semantics, compiles more quickly, and generates far less code.

**Comment by xiongtx** [comment]
Cool, per [discussion on Clojurians](https://clojurians.slack.com/archives/CFFTD7R6Z/p1657573696876719) I think the main effort should be on `meander.zeta`, so I'll close this.

**Comment by xiongtx** [comment]
Looks like not much work is happening on this project, including on the `zeta` branch.

But if @noprompt gets back to it, I opened a [PR](https://github.com/noprompt/meander/pull/251) to fix the $$2^N$$ `OR` branching issue.
