### ISSUE TITLE
The escaping example with `~(+ ?x ?y)` doesn't work on HEAD

### ISSUE THREAD

**Issue by xificurC** [noprompt/meander#44]
```
Syntax error compiling at (REPL:3:21).
Unable to resolve symbol: ?x in this context
```

**Comment by noprompt** [comment]
@xificurC Are your referring to this example?

```clj
;; The first two elements summed together equals the third.
(let [f (fn [z]
          (r.match/match z
            [?x ?y ~(+ ?x ?y)]
            :yes
            _
            :no))]
  [(f [1 2 3])
   (f [2 1 4])
   (f [1 3 4])])
;; =>
[:yes :no :yes]
```

I just tried this out and it seems to work as described in the README.

**Comment by xificurC** [comment]
Hi @noprompt , yes.

```clojure
08:51:23 code/meander % cat .git/refs/heads/delta
d7aa0f697b2ceede58db8b2e3e8ab5a5299a9926
08:51:29 code/meander % clj -r
Clojure 1.10.0
user=> (require '[meander.match.delta :as r.match])
nil
(let [f (fn [z]
          (r.match/match z
            [?x ?y ~(+ ?x ?y)]
            :yes
            _
            :no))]
  [(f [1 2 3])
   (f [2 1 4])
   (f [1 3 4])])
Syntax error compiling at (REPL:3:21).
Unable to resolve symbol: ?x in this context
```

This works:

```clojure
(let [f (fn [z]
          (r.match/match z
            [?x ?y (and ?z (guard (= ?z (+ ?x ?y))))]
            :yes
            _
            :no))]
  [(f [1 2 3])
   (f [2 1 4])
   (f [1 3 4])])
[:yes :no :yes]
```

**Comment by noprompt** [comment]
@xificurC Okay, I was able to get the error. I see the problem now. The macro expansion comes out something like

```clj
(let [target__9823 z fail__9824 (fn [] :no)]
  (if (vector? target__9823)
    (if (= (count target__9823) 3)
      (let [nth_0__9829 (nth target__9823 0)
            nth_1__9830 (nth target__9823 1)
            nth_2__9831 (nth target__9823 2)]
        (if (= nth_2__9831 (+ ?x ?y))
          (let [?x nth_0__9829] (let [?y nth_1__9830] :yes))
          (fail__9824)))
      (fail__9824))
    (fail__9824)))
```

which tells me that it's a prioritization problem and, indeed, it is. I'll patch this real quick!

**Comment by xificurC** [comment]
Glad you found the problem so quickly. How come you weren't getting an error? The expansion you posted is invalid code. Are some parts of the codegen non-deterministic?

**Comment by noprompt** [comment]
@xificurC Should be fixed now. I just pushed up `[meander/delta "0.0.111"]`. I tried it locally in an empty project and it seems to work fine. Thanks for opening up the issue.

> How come you weren't getting an error? Are some parts of the codegen non-deterministic?

I was working in a separate project earlier which was using older version. I should have checked that before replying earlier. Apologies! The compiler is deterministic and this pattern should compile consistently.

**Comment by xificurC** [comment]
No problem, I only realized during the weekend that I wrote you I tested on `HEAD` whereas I actually just pulled 0.0.100. This time I was lucky and you weren't :)

Is there some research paper or something based on what you are operating? I love a good read. It would be nice to mention it in the README as well. A comparison with `core.match`, `core.logic`, `specter` and maybe others would be cool too, so the readers can relate and compare.

**Comment by noprompt** [comment]
@xificurC There are a number of papers and books I have drawn inspiration from. I plan to check in a comprehensive list of resources in a document at some point. For pattern matching, I consulted all of the papers mentioned in the `core.match` wiki as well as others mentioned elsewhere. For logic programming, I've read up on mini-kanren, Prolog, etc. For Term Rewriting (TR), I started with a few resources such as [Term Rewriting and All That](https://www.amazon.com/Term-Rewriting-That-Franz-Baader/dp/0521779200), and Chapters 8 and 9 of the [Handbook of Automated Reasoning](https://en.wikipedia.org/wiki/Handbook_of_Automated_Reasoning). I've also played with several Term Rewriting Systems (TRSs) such as [Maude](https://en.wikipedia.org/wiki/Maude_system), [StrategoXT](https://en.wikipedia.org/wiki/Stratego/XT), and, of course, Mathematica.

These spaces are rich with information and I consider myself a novice with respect to TR. I would also consider Meander to be in the early stages of development with respect to TR. The main focus of my efforts has been on making the pattern matching and substitution parts of the project fast, and crafting the syntax. I believe there is tremendous value in symbolic manipulation in general so this is why I've applied most of my focus in these areas. I think the strategy portion of the library is useful too and hope to spend some time improving it this year. 

If you have ideas on how to improve the project please submit them. Again, these spaces are quite rich and acquiring the expertise needed to benefit the project in meaningful ways takes years to accumulate. I explicitly rely on the help of others. 😄

**Comment by xificurC** [comment]
Thank you @noprompt for that detailed answer! Much appreciated. I might just get some of those books to get my feet wet :)

My enthusiasm span is unfortunately really poor, but it is yours right now, so if you have any tips where to look in the codebase I can try to look around. I'm not really familiar with the internals of pattern matching or the other topics but I might be able to optimize some parts of the code. Do you know of any places that are easy wins WRT to performance?

When writing out the use cases in the readme I noticed this runs around 10x slower than a `filter`:

```clojure
(find [1 2 3 4 5] [_ ... 4 . _ ... ] 4)
```

Running it through a [profiler](https://github.com/clojure-goes-fast/clj-async-profiler) showed that more than third of the time is spent in `partitions`. Maybe a custom Iterable/Reducible could tone that down.

Sorry to turn this issue into an off-topic conversation. I'll be happy to continue somewhere else. E.g. I sit on [the clojurians zulip](https://clojurians.zulipchat.com/) every workday.

Thank you for your time

**Comment by jimmyhmiller** [comment]
@xificurC Check this issue out for more information about the problem you mentioned here. https://github.com/noprompt/meander/issues/45
