### ISSUE TITLE
Please add license information 

### ISSUE THREAD

**Issue by vijaykiran** [noprompt/meander#58]
I can't find any info on what type of license this project uses. I think this is critical piece of information about the source code which will help using the project.

**Comment by noprompt** [comment]
Sure thing. I will add a license to the project soon. Thanks for pointing this out! 👍

**Comment by jimmyhmiller** [comment]
@vijaykiran We decided on MIT and added it to the repo https://github.com/noprompt/meander/blob/delta/LICENSE. Sorry we missed that before. Thanks for pointing it out.
