### ISSUE TITLE
typo in rp+-test ?

### ISSUE THREAD

**Issue by daslu** [noprompt/meander#61]
Thank you for this brilliant library!

https://github.com/noprompt/meander/blob/delta/test/meander/substitute/delta_test.cljc#L53

```
(t/deftest rp+-test
  (t/is (= [:A :A :A :A]
           (r.substitute/substitute [:A ..4])))

  (let [!1s [:X :O :X :O]
        !2s [1 2 3 4]]
    (t/is (= [:X 1 :O 2 :X :O 3 4])
          (r.substitute/substitute [!1s !2s ..2 !1s ... !2s ...]))))

```

The last equality's parens seems misplaced, IIUC.

**Comment by noprompt** [comment]
@daslu That's definitely a typo. Were you able to verify the test passes upon fixing it? If it does, and you feel comfortable patching it, I'd accept and merge a patch for that.

**Comment by noprompt** [comment]
This typo was caught and does not exist on the `epsilon` branch.

**Comment by daslu** [comment]
Yes, at the current `delta` branch, all tests pass after fixing it.
Thanks, I can do a pull request a little later today.

**Comment by noprompt** [comment]
This has been fixed in `epsilon` which is not the main branch of the project. If you'd still like to submit a patch to the `delta` branch, please feel free.
