### ISSUE TITLE
Blogpost for practical meander has ending slash causing 404

### ISSUE THREAD

**Issue by MageMasher** [noprompt/meander#69]
Currently the blog post section has a link pointing at:
`https://jimmyhmiller.github.io/meander-practical/` which 404's while
`https://jimmyhmiller.github.io/meander-practical` (No trailing slash) succeeds.

Not sure if this is an issue for the meander project or @jimmyhmiller (or both)

**Comment by jimmyhmiller** [comment]
Thanks for pointing this out. I fixed the link here and will hopefully make my site handle both. I must have introduced this problem yesterday on upgrade.
