### ISSUE TITLE
n-or-more has an off by one error

### ISSUE THREAD

**Issue by dgr** [noprompt/meander#72]
Consider this Meander-based function to split names into first and last parts (yes, I know the real world is more complex than this for names, but this is the smallest function that highlights the issue):

```
(defn split-full-name-1
  [full-name]
  (let [names (str/split full-name #" ")]
    (meander/find names
      [!firsts ..1 ?last]
      [!firsts ?last])))
```

Note that I'm using !firsts with ..1 so that I can match multiple first names (e.g., "John Paul" or "Mary Beth").

Consider the results this gives for some common cases:
```
> (split-full-name "JOHN PAUL DOE")
[["JOHN" "PAUL"] "DOE"]   ;;; Works as expected
> (split-full-name "MADONNA")
nil         ;;; Works as expected
> (split-full-name "JOHN DOE")
nil    ;;; Wait, what????
```

If I change it to zero-or-more ("...") then it works. But is that right? Shouldn't I be able to force it to match once in any case. The real problem I'm working on requires lots of other patterns (to deal with the full complexity), but the fact that this one is not matching as expected has thrown me off.

**Comment by dgr** [comment]
I should also say that if I use "..." instead of "..1", then when I call the function on "MADONNA" then I get "[[] "MADONNA"]" as the output instead of nil, which is not what I want. Basically, I want something that matches 2+ names, with the first n-1 names landing in !firsts and only the last landing in ?last, and not matching for 0 or 1 names.

**Comment by dgr** [comment]
Also, this is with Epsilon 0.0.187 from Clojars (latest as-of today).

**Comment by noprompt** [comment]
@dgr Thanks for the report. I've been able to reproduce the bug. I'll fix it as quickly as I can.

**Comment by dgr** [comment]
Thank you. No worries. Glad to know that it wasn't pilot error on my part. :-) I kept reading and re-reading the documentation to make sure I hadn't screwed something up. This is my first time using Meander in anger, having looked at it a year or so ago. I'm still getting the hang of it.

**Comment by dgr** [comment]
BTW, I should also say that when it works, it's really amazing in terms of how much it simplifies my logic. I can see that it's going to be a strong tool for me going forward.

**Comment by noprompt** [comment]
@dgr I have found the bug and am working to fix it. Thanks for reporting the bug!

I'm glad you're finding the project interesting. As soon as I get this fixed "when it works" should include this case too. 😉

**Comment by noprompt** [comment]
@dgr This his been [fixed](https://github.com/noprompt/meander/blob/epsilon/test/meander/epsilon_test.cljc#L2106-L2122) along with several other problems.

**Comment by dgr** [comment]
@noprompt , thanks!
