### ISSUE TITLE
Zero or more patterns without prefix cause invalid code

### ISSUE THREAD

**Issue by jimmyhmiller** [noprompt/meander#8]
Improper use of the zero or more pattern is not caught early and results in invalid code generation. I discovered this while playing around with meander before I understood how `...` worked. (Though I must admit I'm still not sure how to properly express what I was hoping to with the code below).

```clojure
user=> (m/match [1 2 3] [... ?x] ?x)

CompilerException java.lang.RuntimeException: Unable to resolve symbol: ?x in this context, compiling:(NO_SOURCE_PATH:2:1) 
```

If we look at what this pattern parses to it makes sense why it would generate incorrect code.

```clojure
user=> (require '[meander.syntax.alpha :as syntax])
user=> (syntax/parse '[... ?x])
[:lit [... ?x]]
```

Because of the way the parsing works with spec, this invalid syntax is falling through to the literal catch all case. It is not treating `?x` as a logic variable. We can see that result in the macro-expanded code.

```clojure
(let*
 [target__16298
  [1 2 3]
  fail__16299
  (clojure.core/fn
   []
   (throw (java.lang.Exception. "non exhaustive pattern match")))]
 (if (clojure.core/= target__16298 ['... '?x]) ?x (fail__16299)))
````

As I see it there are a few possible resolutions. 

1. We could fix the code to interpret `?x` here as an lvar and keep `...` as just a literal. Personally this doesn't seem intuitive behavior so I'd recommend against it.
2. We could add to the syntax tree a special case for this invalid use. This seems inelegant and counter intuitive. While we will certainly have some parses that are semantically incorrect, it seems weird to have an invalid parse represented as a node in the parse tree.
3. We could make the parse of `:meander.syntax.alpha/zero-or-more` a bit more forgiving by changing `s/+` to `s/*` [here](https://github.com/noprompt/meander/blob/530c7c3b57d4093d3638aefb339f9cc614de6002/src/meander/syntax/alpha.clj#L217)

By doing this, we would get a different parse tree that reflects a bit more the intent I had when writing this.

```clojure
user=> (syntax/parse '[... ?x])
[:seq
 [:prt
  {:left [:rp* {:dots ...}],
   :right [:prt {:left [:cat [[:lvr ?x]]]}]}]]
```

This might seem like a weird suggestion, as it now allows invalid code to be accepted. But we can fix this by adding in a [check condition for the `:rp*` node](https://github.com/noprompt/meander/blob/alpha/src/meander/match/alpha.clj#L1220-L1230). Perhaps something with a message like:

```
Zero or more (...) is a postfix operator. It must have some value in front of it. (i.e. [1 ... ?x])
```

It may also be helpful to tell people how to accomplish what I am trying to accomplish here, but I am not sure how to do that myself. (In this case I'd be saying find the last element of the list, but I really just want to say, I don't care what is to the left of this ?x I'm looking for)

Personally I think 3 makes a lot of sense. But as I lack familiarity of the code base, I wanted to talk to you before trying to implement anything. I'd love to implement the fix myself to get familiar with the workings of the code base. As well as add some tests around this.

If you have a different suggestion I'd love to hear it. 

Here is a command to recreate the issue.
``` bash
clj -Sdeps '{:deps {noprompt/meander {:git/url "https://github.com/noprompt/meander.git" :sha "530c7c3b57d4093d3638aefb339f9cc614de6002"}}}' \
"(require '[meander.match.alpha :as m]) (m/match [1 2 3] [... ?x] ?x)"
```

**Comment by noprompt** [comment]
@jimmyhmiller Thanks for the excellent report! 

This was a corner case I knew about but had not addressed yet. I agree with your survey and I think that 3 is the most appropriate route here. The proposed solution seems sound. Nice work connecting all the dots!

Do you feel comfortable patching it?

**Comment by noprompt** [comment]
We'll likely want to address `:rp+` as well. We could do that separately but I'm fine with it being solved in the same patch.
