### ISSUE TITLE
`with` example (docs) broken in epsilon

### ISSUE THREAD

**Issue by marioaquino** [noprompt/meander#83]
The example from this [link](https://github.com/noprompt/meander/blob/epsilon/doc/pattern-matching.md#with) returns `nil` instead of:
```
[[:div :p :strong :em :u :ul :li :li :li :li]
 [{"foo" "bar"} {"baz" "quux"}]
 ["Foo" "Bar" "Baz" "Beef" "Lamb" "Pork" "Chicken"]]
```

**Comment by jimmyhmiller** [comment]
`or` should have been updated to be namespaced (`m/or`). I fixed it and verified that it is working. Thanks for filing the issue.

**Comment by marioaquino** [comment]
Works as advertised.  Thanks, @jimmyhmiller!
