### ISSUE TITLE
Multiple ignore _ ... patterns produce duplicate matches

### ISSUE THREAD

**Issue by timothypratley** [noprompt/meander#96]
When using many ignore patterns:

```clojure
(m/search [1 2 3 4 5]
          [1 . _ ... 2 . _ ... ?x & _]
          ?x)
=> (3 4 5 4 5 5)
```
Expected `(3 4 5)` as there are only 3 ways to match the pattern, but got extra redundant answers.

Using named patterns instead of `_` avoids this:

```clojure
(m/search [1 2 3 4 5]
          [1 . !a ... 2 . !b ... ?x . !c ...]
          ?x)
=> (3 4 5)
```
This behavior affects `separated` syntax

**Comment by jimmyhmiller** [comment]
This is really interesting. I will try to dig into this to understand what is going on with the code generation here. Thanks for reporting.

**Comment by noprompt** [comment]
The bug is probably located under [this line](https://github.com/noprompt/meander/blob/epsilon/src/meander/match/epsilon.cljc#L965) and might have something to with the call to `window` [here](https://github.com/noprompt/meander/blob/epsilon/src/meander/match/epsilon.cljc#L968).

**Comment by noprompt** [comment]
I reverted an attempted optimization I made a while back. It was the culprit. I'll have to come back to the work I was attempting to do there at some point. Anyway, this is fixed.
